import Head from 'next/head'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import { useUser } from '@auth0/nextjs-auth0/client'
import LandingPage from '../components/LandingPage'
import PanelBody from '../components/PanelBody'
import { BrowserRouter } from 'react-router-dom';

export default function Home() {
  const { user, error, isLoading } = useUser();
  if (isLoading) return <div>Loading...</div>
  if (error) return <div>{error.message}</div>
  
  return (
    <>
    <BrowserRouter basename="/">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/antd/dist/antd.min.css" />
      </Head>
      <main>
          { !user && <LandingPage /> }
          { user && <PanelBody /> }
      </main>
      </BrowserRouter>
    </>
  )
}
