import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
import { useUser } from '@auth0/nextjs-auth0/client'


export default function Home() {
  const { user, error, isLoading } = useUser();
  console.log("user: ", user);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Link href="/api/auth/login">login</Link>
          <Link href="/api/auth/logout">logout</Link>
          <Link href="/api/auth/me">me</Link>
          
      </main>
    </>
  )
}
